[package]
name = "confetti_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
colored = "2.1.0"
directories = "5.0.1"
dirs = "5.0.1"
futures = "0.3.31"
indicatif = "0.17.8"
moro = "0.4.0"
moro-local = "0.4.0"
reqwest = { version = "0.12.8", features = ["multipart", "json", "stream"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["fs", "macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.12", features = ["codec"] }
toml = "0.8.19"
uuid = { version = "1.11.0", features = ["serde", "v4"] }
